<?php

/**
 * LOCAL, STAGING, or PRODUCTION
 */
$ENVIRONMENT          = 'LOCAL';

/**
 * Automated mailer
 */
$AUTO_MAIL_NAME       = '';
$AUTO_MAIL_EMAIL      = '';

/**
 * The sendee for outgoing mail
 */
$RECIPIENT_NAME       = '';
$RECIPIENT_EMAIL      = '';

/**
 * Connecting to the SMTP server
 */
$MAIL_CLIENT_HOST     = '';
$MAIL_CLIENT_USERNAME = '';
$MAIL_CLIENT_PASSWORD = '';
$MAIL_CLIENT_OUTGOING = 587;

putenv("ENVIRONMENT=$ENVIRONMENT");
putenv("AUTO_MAIL_NAME=$AUTO_MAIL_NAME");
putenv("AUTO_MAIL_EMAIL=$AUTO_MAIL_EMAIL");
putenv("RECIPIENT_NAME=$RECIPIENT_NAME");
putenv("RECIPIENT_EMAIL=$RECIPIENT_EMAIL");
putenv("MAIL_CLIENT_HOST=$MAIL_CLIENT_HOST");
putenv("MAIL_CLIENT_USERNAME=$MAIL_CLIENT_USERNAME");
putenv("MAIL_CLIENT_PASSWORD=$MAIL_CLIENT_PASSWORD");
putenv("MAIL_CLIENT_OUTGOING=$MAIL_CLIENT_OUTGOING");